const Events = {
  LEFTBUTTONCLICK: "LEFTBUTTONCLICK",
  RIGHTBUTTONCLICK: "RIGHTBUTTONCLICK",
  RESTARTBUTTONCLICK: "RESTARTBUTTONCLICK",
  DONEBUTTONCLICK: "DONEBUTTONCLICK",
  CLOCK_TICK: "CLOCK_TICK",
  DISPLAY_RESOLUTION_CHANGE: "DISPLAY_RESOLUTION_CHANGE"
};

export default Events;
